AirArkanoid: Fix python3 on Windows
flipperdevices/flipperzero-good-faps pull request #155
Opened 2024-03-04 06:31 UTC by Willy-JL

# What's new

- Fallback to `python` when `python3` is not available for Air Arkanoid

# Verification 

- Compile Air Arkanoid on Windows, it works (`python3` is not a thing on Windows)

# Notes

- `python3` isn't really ideal, the best solution would be just using `python` on linux too, but the toolchain doesn't include it
- fbt simply `exec()`'s the content of the manifest
  - it would be possible to improve readability of this by defining variables, but it would cause pollution in the fbt namespace
  - this also creates a lot of questions regarding the safety of this...? manifests seem pretty much free code execution to someone downloading and compiling an app blindly
- havent tested on ufbt

# Checklist (For Reviewer)

- [ ] PR has description of feature/bug or link to Confluence/Jira task
- [ ] Description contains actions to verify feature/bugfix
- [ ] I've built this code, uploaded it to the device and verified feature/bugfix

2024-03-04 20:32 UTC, Willy-JL commented
just found out that some distributions of python for windows do include python3, while fbt does not, so it would fall back to the system python incorrectly...

2024-03-06 13:44 UTC, hedger requested changes, later dismissed
You can just use `${PYTHON3}` ;)

2024-03-07 05:09 UTC, skotopes approved these changes

2024-03-07 05:12 UTC, skotopes commented
Nice catch. Thanks.

2024-03-07 05:12 UTC, merged